#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ ! -f "${PWD}/config/configuration.yaml" ]; then
  mkdir -p "${PWD}/config"
  hass --config "${PWD}/config" --script ensure_config
  echo "Creating default configuration."
  echo "
default_config:

logger:
  default: info
  logs:
    custom_components.bodymiscale: debug

# Example configuration.yaml entry
input_number:
  weight:
    name: Weight
    initial: 70
    <<: &weight_options
      min: 10
      max: 200
      step: 0.1
  impedance:
    name: Impedance
    initial: 400
    <<: &impedance_options
      min: 0
      max: 3000
      step: 1

  weight_2:
    name: Weight 2
    initial: 80
    <<: *weight_options
  impedance_2:
    name: Impedance 2
    initial: 800
    <<: *impedance_options

template:
  - sensor:
      - name: Weight
        state: "{{ states('input_number.weight') }}"
        unit_of_measurement: "kg"
      - name: Impedance
        state: "{{ states('input_number.impedance') }}"
        unit_of_measurement: "ohm"
      - name: Weight 2
        state: "{{ states('input_number.weight_2') }}"
        unit_of_measurement: "kg"
      - name: Impedance 2
        state: "{{ states('input_number.impedance_2') }}"
        unit_of_measurement: "ohm"

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
#   wait: true
" >> "${PWD}/config/configuration.yaml"
fi

# Set the python path to include our custom_components directory
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Start Home Assistant
hass --config "${PWD}/config" --debug