#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

pre-commit install-hooks;
pre-commit run --hook-stage manual --all-files;

#bellybutton lint

#vulture . --min-confidence 75 --ignore-names policy
