#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

scripts/install/pip_packages "pip"
scripts/install/pip_packages setuptools wheel
scripts/install/pip_packages --requirement requirements.txt
pre-commit install
