name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  schedule:
    - cron: "0 0 * * *"

env:
  DEFAULT_PYTHON: "3.14"

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    name: Validate with HACS
    steps:
      - uses: "actions/checkout@v7"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"

  validate-hassfest:
    runs-on: "ubuntu-latest"
    name: Validate with Hassfest
    steps:
      - uses: "actions/checkout@v7"
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  code-quality:
    runs-on: "ubuntu-latest"
    name: Check code quality
    steps:
      - uses: "actions/checkout@v7"
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e ".[dev]"
      - name: Run Ruff check
        run: ruff check --fix custom_components/ tests/
      - name: Run Ruff format check
        run: ruff format --check custom_components/ tests/
      - name: Run mypy
        run: mypy custom_components/
      - name: Pylint review
        run: pylint custom_components/
      - name: Run tests
        run: python -m pytest
